spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/hammer-backend?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties:
      druid:
        stat:
          mergeSql: true
          slowSqlMillis: 5000
  messages:
    encoding: utf-8

  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.onehammer.backend.demo.entity

  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8089
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /api




token:
  expirationSeconds: 3600
  validTime: 7

